[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "https://sozu.io"
version = "0.15.2"
license = "LGPL-3.0"
authors = [
  "Geoffroy Couprie <geo.couprie@gmail.com>",
  "Eloi Demolis <eloi.demolis@clever-cloud.com>",
  "Emmanuel Bosquet <emmanuel.bosquet@clever-cloud.com>",
  "Florentin Dubois <florentin.dubois@clever-cloud.com>",
]
categories = ["network-programming"]
edition = "2021"
rust-version = "1.66.1"
include = [
  "./README.md",
  "Cargo.toml",
  "src/**/*",
  "assets/certificate.pem",
  "assets/key.pem",
  "assets/404.html",
  "assets/503.html",
]

[dependencies]
anyhow = "^1.0.72"
hex = "^0.4.3"
libc = "^0.2.147"
log = "^0.4.19"
time = "^0.3.23"
toml = "^0.7.6"
memchr = "^2.5.0"
mio = { version = "^0.8.8", features = ["os-poll", "net"] }
nix = "^0.26.2"
nom = "^7.1.3"
pem = "^2.0.1"
prost = "^0.11.9"
rand = "^0.8.5"
serde = { version = "^1.0.171", features = ["derive"] }
serde_json = "^1.0.103"
sha2 = "^0.10.7"
trailer = "^0.1.2"
pool = "^0.1.4"
poule = "^0.3.2"

[features]
unstable = []
logs-debug = []
logs-trace = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }

[build-dependencies]
prost-build = { version = "^0.11.9" }
