[package]
name = "sozu-e2e"
version = "0.15.0"
rust-version = "1.66.1"
edition = "2021"

[dependencies]
futures = "^0.3.28"
futures-lite = "^1.13.0"
hyper = { version = "^0.14.26", features = ["client", "http1"] }
hyper-rustls = { version = "^0.24.0", default-features = false, features = ["webpki-tokio", "http1", "tls12", "logging"] }
libc = "^0.2.146"
mio = "^0.8.8"
rustls = { version = "^0.21.2", features = ["dangerous_configuration"] }
serial_test = "^2.0.0"
slab = "^0.4.8"
time = "^0.3.22"
tokio = { version = "1.28.2", features = ["net", "rt", "rt-multi-thread"] }

sozu-command-lib = { version = "^0.15.0" }
sozu-lib = { version = "^0.15.0" }