[package]
name = "sozu-e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
sozu-lib = { path = "../lib" }
sozu-command-lib = { path = "../command" }
slab = "^0.4.7"
mio = "^0.8.5"
time = "^0.3.17"
futures = "^0.3.26"
libc = "^0.2.139"
serial_test = "^1.0.0"